### ISSUE TITLE
Print output of build steps on stdout/stderr

### ISSUE THREAD

**Issue by jespersmith** [colcon/colcon-core#102]
When debugging build scripts and during development, having to open the logs to get information why things failed is a huge time sink.

How do I output the build progress on the command line (probably in sequential mode)?

**Comment by dirk-thomas** [comment]
Actually by default all the output to `stderr` is being shown after each package finished.

For showing output from `stdout` immediately please see the documentation for this feature: https://colcon.readthedocs.io/en/latest/user/how-to.html#show-all-output-immediately-on-the-console

If you build packages in parallel `--event-handlers console-cohesion+` might be the better option since it only prints all output after each package has finished which avoids interleaving the output from multiple packages.

`colcon build --help` will also provide information about each and every option available.

**Comment by jespersmith** [comment]
Thanks, that will be awesome for development!
