### ISSUE TITLE
Package configuration syntax is inconsistent

### ISSUE THREAD

**Issue by KazNX** [colcon/colcon-core#105]
Hi,

I've been playing around with package configuration - specifically setting CMake options - and I've identified the three different configuration files using two different configuration syntaxes:

1. Global configuration using `COLCON_DEFAULTS_FILE` environment variable and/or `defaults.yaml` (YAML) file
2. Package specific configuration using `colcon.meta` (YAML) file in the project root
3. Package specific configuration using `colcon.pkg` (JSON) file in the package root

Two of these are YAML based, and one is JSON, while the available keywords are consistent between them. For example, I can specify `cmake-args` in any of the three files.

Is there a good reason for having the `colcon.pkg` file use JSON and not YAML?

**Comment by dirk-thomas** [comment]
There is reason the parsing of `colcon.pkg` uses JSON at the moment. That was just the way it was implemented initially. The [documentation](https://colcon.readthedocs.io/en/latest/user/configuration.html#configuration) even says:

> All files described below are using the YAML format.

Since YAML is a superset of JSON this can easily be changed to be parsed as YAML, see colcon/colcon-meta#7.

**Comment by KazNX** [comment]
Thanks for the update. I see you already have a fix waiting to be integrated.
