### ISSUE TITLE
Distributing debian packages

### ISSUE THREAD

**Issue by murphm8** [colcon/colcon-core#119]
Hi @dirk-thomas,

I see that python3-colcon-core and other debian package builds of colcon packages are available from packages.ros.org. How is that build and distribution set up?

Thanks,
Matt

**Comment by dirk-thomas** [comment]
All ROS Python packages (e.g. `catkin_pkg`) as well as the `colcon` packages are released using the helper script in the [ros_release_python](https://github.com/ros-infrastructure/ros_release_python/) repository. The script is a simple wrapper around `twine` (for Python release to PyPI) and `stdeb` (for Debian packages - Python 2 as well as Python 3 pkgs).

A developer runs that script locally which at the end uploads the artifacts to PyPI and/or the ROS bootstrap apt repo (see [dput.cf](https://github.com/ros-infrastructure/ros_release_python/blob/4019e4cb413015d16d3ec46adb126e7dfede49e2/resources/dput.cf)). For `colcon` packages only the `pip` and `deb3` target are generated since Python 2 isn't supported.

* For the PyPI release the developer needs to have an account on PyPI and have the permission to push new releases for that package. For `colcon` packages that is usually the author which made the first release, but more maintainers can be added for the PyPI package through the web interface.
* For the Debian packages - since the upload requires SSH access to the server containing the `bootstrap` repo (which contains these Python packages as well as third-party Debians we import from "upstream") - only OSRF people can publish those. Commonly after uploading a new Debian package we trigger the `import_upstream` job on the Jenkins buildfarm to pull in the new packages to the ROS package repositories. If non-OSRF maintainers want to have their `colcon` packages also released as Debian packages they can proceed with the PyPI release on their own whenever they are ready and then ask (e.g. by creating a ticket mentioning me to request a Debian release to be made).

**Comment by murphm8** [comment]
Thanks for the expansive explanation! I'll create an issue in my packages for creating debs when we are ready for that. Closing this issue.
