### ISSUE TITLE
Is macOS CI planned?

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-core#12]
I was wondering if there is a plan to run MacOS jobs in travis in the future or if it's considered not useful as the behavior should be very similar to Linux as all this would test is Python and sh.

Different but related, should more recent versions of Python be tested as well (as Windows, MacOS and recent Ubuntu ship with 3.6.5) ?

**Comment by dirk-thomas** [comment]
I didn't add macOS and/or Python 3.6 until now since I don't see what they would cover beside Linux with Python 3.5. If there is a compelling reason / cases which would benefit from those both could be added to the CI.

My experience with macOS builds on Travis is that they are often very slow / wait in the queue long until they are being processed which would be discouraging to provide quick feedback on PRs.

**Comment by mikaelarguedas** [comment]
Thanks for answering, I think this can be closed then.

I think testing Python 3.6 (at least on Windows) is relevant as this is what users would use on an up-to-date Windows system.

**Comment by dirk-thomas** [comment]
I created #15 to use Python 3.6 on AppVeyor.
