### ISSUE TITLE
Colcon vs. catkin_make for ROS1

### ISSUE THREAD

**Issue by murphm8** [colcon/colcon-core#149]
Hi Dirk,

Can you comment on using `colcon` vs `catkin_make` for building ROS1 applications?  Is `colcon` the recommended build tool going forward?

Thanks,
Matt

**Comment by dirk-thomas** [comment]
At the moment we don't plan to change the recommended build tool for ROS 1. Not because it doesn't work but more over the amount of effort this would require (considering the numerous places where this is being embedded in documentation, tutorials, etc.). We simply can't commit that level of effort necessary for such a transition. E.g. `catkin_tools` has been around for a long time and has been actively used by many user but hasn't been the recommended build tool. `colcon` is kind of similar. We encourage people to try it though and will address problems if there are any.

As a side note: the `ros_buildfarm` is capable of using `colcon` for ROS 1 distributions. If we could create `colcon`-based devel jobs in parallel to the existing `catkin_make_isolated`-based devel jobs and demonstrate that their results are equal that would be an important milestone to build confidence that `colcon` could replace `catkin_make_isolated`. But there are several other use cases, e.g. cross compilation, which have to be demonstrated too in order to confidently recommend it.

**Comment by dirk-thomas** [comment]
Assuming my comment answered your question I will go ahead and close this ticket.
