### ISSUE TITLE
Colcon runs in global interpreter

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#181]
The colcon executable installed through apt has a shebang of `#!/usr/bin/python3`.
This prevents use in different virtual environments, especially since this shebang then puts the global python shebang into scripts built with colcon.

One (or more) of the following would make this easier:
- Recommended to install colcon-core locally (instead of globally with apt as per https://colcon.readthedocs.io/en/released/user/installation.html).
- Change the shebang on colcon to `/usr/bin/env python3`.
- Colcon should respect the Python interpreter specified with `$COLCON_PYTHON_EXECUTABLE` when building other python projects.

```
➜  ros2_ws git:(master) ✗ cat `which colcon`
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'colcon-core==0.3.20','console_scripts','colcon'
__requires__ = 'colcon-core==0.3.20'
import re
...
```

**Comment by dirk-thomas** [comment]
> Recommended to install colcon-core locally (instead of globally with apt as per https://colcon.readthedocs.io/en/released/user/installation.html).

On Debian systems we do recommend to install Debian packages since they are being updated by `apt`. Using `pip` instead requires the user to update the packages manually which is not desired.

In the use case with a virtual environment you can install `colcon` into that venv using `pip`.

> Change the shebang on colcon to `/usr/bin/env python3`.

The shebang line is generated by the Python `setuptools` package. I don't think `colcon` has a way to influence that. If there is something we can do different please let us know how to achieve that.

Again in the use case with a virtual environment if you install `colcon` into that venv using `pip` it should used the absolute path to the Python interpreter used in that venv.

> Colcon should respect the Python interpreter specified with `$COLCON_PYTHON_EXECUTABLE` when building other python projects.

That sounds like a good idea. Please consider to create a pull request for this enhancement.

**Comment by rotu** [comment]
I've had considerable difficulty with figuring this out, but I'm making progress and you will have a pull request (or two).

> The shebang line is generated by the Python `setuptools` package. I don't think `colcon` has a way to influence that. If there is something we can do different please let us know how to achieve that.

Putting this in setup.cfg causes the shebang to be as desired for both `pip install` and `colcon build`:
```
[build_scripts]
executable=/usr/bin/env python3
```
Hard lessons from playing around with this:
- This setting is *not* respected when using `pip install`'s `-e`/`--editable` option
- When testing this, use the pip `--no-cache-dir` flag.
