### ISSUE TITLE
install progress doesnt reflect actual progress

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-core#19]
opening to keep a public trace of it:

Currently the status bar displays a percentage of progress for the install step.
Hypothesis: it it using the progress over the targets but not the installed files
Consequence: projects with many files to install but few targets (e.g. message packages) display 100% all the time and it doesnt reflect the actual progress of the install step

**Comment by dirk-thomas** [comment]
`make` indeed only prints percentage over the checked targets. The copying of files during the install step afterwards does neither print any progress nor is affecting the percentage of the progress on the targets.

The options I see:
1. Disable the progress extraction for `install`
  * The downside would be that if a different build system output viable progress that would not be available
2. Apply custom logic to the `install` progress (like scale 100% down to only e.g. 90%)
  * Same downside as the previous option
  * Pretty arbitrary since the progress would be "stuck" at 90% for an indefinite amount of time and then just complete.
3. Just keep it as is since that is the information `make install` provides us with.

Please comment with the option you would prefer or suggest an additional one.

**Comment by mikaelarguedas** [comment]
I'm fine keeping it as is, as any other alternative would not necessarily be "better" and "worse" in some situations.

For packages with targets and not many files: information is pretty accurate and thus valuable
For build systems providing accurate progress: being able to display progress is valuable

I guess documenting the current behavior would be enough

**Comment by dirk-thomas** [comment]
> I guess documenting the current behavior would be enough

Do you have a suggestion where to put that piece of documentation?

**Comment by dirk-thomas** [comment]
I will go ahead and close this for now since we can't change the reported percentage of `make install`, I don't think the information available should be dropped and I don't see a good place to add documentation for it and don't think it is important to be documented.
