### ISSUE TITLE
`colcon build` on OSX is orders of magnitude slower than direct `make`

### ISSUE THREAD

**Issue by emersonknapp** [colcon/colcon-core#193]
I have a workspace set up on Mac with source checked out from https://github.com/ros2/ros2/blob/master/ros2.repos

On: Macbook Pro 15 inch 2017, 2.9 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3
Running High Sierra 10.13.6

Using https://github.com/ros2/rcl/blob/master/rcl/test/rcl/test_events.cpp as example file, arbitrarily chosen - triggers minimal rebuild because it is a leaf executable.

* Build once from nothing `colcon build --packages-up-to rcl`
* Change one line in example file, then `colcon build --packages-select rcl`
    * Takes ~5 minutes to complete
* Change one line then `cd build/rcl; make install`  note that this is single threaded
    * ~15 seconds
* Change one line then `cd build/rcl; make -j$(sysctl -n hw.logicalcpu) install`
    * ~7 seconds

There is of course some overhead to be expected from the tool, but this seems clearly outside the expectation. Probably something weird is going on that makes everything go really slow.

**Comment by dirk-thomas** [comment]
You might want to try `cmake --build` too since that is what is being used internally by `colcon-cmake`. I wouldn't expect a big difference though.

Please try to run the build with `--event-handlers console_direct+` to get an idea in which phase the build is taking so long.

You could also try to disable all event handlers one by one with `--event-handlers ...-` (see `--help` for a of names).

**Comment by emersonknapp** [comment]
Using `cmake --build` gives me approximately timing as `make -j$(sysctl -n hw.logicalcpu)`

I did notice that `source install/local_setup.zsh` slowed down subsequent `cmake build` calls to about 2minutes each. So the environment seems to have much to do with it, I know that slowdown is not a `colcon` thing, that would be on the `ament` side. But that's still twice as fast as running through `colcon` - I will run through the `event-handlers` suggestions once I get a chance, thanks!

**Comment by dirk-thomas** [comment]
> Using `cmake --build` gives me approximately the same timing as `make -j$(sysctl -n hw.logicalcpu)`

Makes sense.

> I did notice that source install/local_setup.zsh slowed down subsequent cmake build calls to about 2minutes each.

Are you sourcing the workspace in the same shell we you later invoke `colcon build`? That is not recommended. You should use two separate shell - one for invoking `colcon build / test` which does **not** have that workspace sourced and a second one were you source the workspace and use anything provided in this workspace.

Can you tried to reproduce the slowdown again with that setup? You should try this workflow with a fresh build - so using newly opened shells which haven't source the workspace before and `build` / `install` wiped.

**Comment by dirk-thomas** [comment]
> Can you try to reproduce the slowdown again with that setup?

@emersonknapp Friendly ping.

**Comment by deitry** [comment]
@dirk-thomas 
> You should use two separate shell

This is the first place ever where I read this advice. I was so much tired of these `source this ; source that`, so I made a couple of aliases and run them automatically in order to just build and run my packages. In fact I discover that there's no need at all in 'source commands', so I make an [extension](https://marketplace.visualstudio.com/items?itemName=deitry.colcon-helper) which do this one single time and put the resulting envs in one single file.

I'm badly amazed of colcon's demands and fragility. No matter how complex the tool is inside, it should be comfortable to use. Or at least it should have clear and complete manuals/examples/tutorials. I cannot believe that someone want to create a system that is more complex to use than to develop.

Is there some article with all 'advices' on how to properly use colcon?

**Comment by dirk-thomas** [comment]
> I'm badly amazed of colcon's demands and fragility.

@deitry You might want to be a more concrete and constructive with your criticism. If you are referring to the fact that you should do "build, change env, build env": I doubt that this is actually specific to `colcon`. You might see unwanted side effects which any kind of build system - simply because you are changing the input to the system.

> No matter how complex the tool is inside, it should be comfortable to use.
> I cannot believe that someone want to create a system that is more complex to use than to develop.

If you have specific suggestions which parts are uncomfortable to use and how to make it more comfortable to use please feel free to bring them up. Just stating your negative opinion here won't help in any way.

> Is there some article with all 'advices' on how to properly use colcon?

You can find the documentation in this repo: https://github.com/colcon/colcon.readthedocs.org - as with any project please feel free to fill (constructive) tickets - either as issues or even better as pull requests.

**Comment by dirk-thomas** [comment]
@emersonknapp I am going to close the ticket for now due to no response. Please feel free to comment with the requested information and if necessary the ticket can be reopened.

**Comment by deitry** [comment]
@dirk-thomas 
Excuse me for my reaction. The statement that I should keep two terminals opened just for different colcon subcommands blowed up my mind. I love the idea of colcon and its goals, I use it in my current project, I try to read any docs I find, but there is also some things I miss - they just came out of nowhere for me, without any visible reason.

I'm looking for optimal workflow, which demands minimum of overhead operations. And the necessity of `source ...` is one of the most annoying thing. And here I found that I'm not even supposed to do this.

**Comment by dirk-thomas** [comment]
> And the necessity of `source ...` is one of the most annoying thing.

If you don't install built packages into the system you do you intent to use them without any environment files? How else than sourcing a script file do you want those environment files to be set/extended?

Sourcing the setup file in a separate shell from where you build the workspace is a **recommendation**. You are free to ignore it and use the same shell. You might never run into the possible side effects but you should be aware of them when you make the decision to do so.
