### ISSUE TITLE
What is the current minimal requirements of colcon to use all the features?

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-core#20]
Knowing the minimal requirements of this tool (such as pytest version)  would help us evaluate the different packaging options.

We know pip packages tend to not be updated by users (I always forget to upgrade them) and it would be very valuable to be able to ship this tool as a deb.

**Comment by dirk-thomas** [comment]
The following changes have been merged:
* "Newer" `pytest` related features are only used when they are available: colcon/colcon-core#39
* The dependencies are explicitly listed now: e.g. colcon/colcon-core#45, colcon/colcon-ros#6

Once Debian packages exist and instructions for using them are being added they need to mention that `pytest-repeat` and `pytest-rerunfailures` need to be installed from PIP.

Is there anything else which should be addressed for this ticket? Otherwise I think it can be closed.

**Comment by mikaelarguedas** [comment]
With https://github.com/colcon/colcon.readthedocs.org/pull/15 this issue is addressed as we have a list of all the dependencies.
This is still missing the minimal versions needed to use all the features, but from my understanding this will be addressed once the package is released.
@dirk-thomas please comment here if this doesn't match your understanding

**Comment by dirk-thomas** [comment]
If there are specific minimum versions required those should be explicitly stated in the `setup.cfg` files of each package as well as in the `requirements.txt` file (see https://github.com/colcon/colcon.readthedocs.org/blob/master/requirements.txt). Atm I don't see specific version numbers necessary.

I can imagine that it wouldn't work with much older `setuptools` / `pytest` versions but the exact constraint are unknown to be at the moment. If we know any specific thresholds they should be added to those files with a brief comment.
