### ISSUE TITLE
Command line words beginning with hyphen treated as package names, not unrecognized arguments

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#325]
Package names after `--packages-select` with leading hyphens are treated as package names, and colcon logs a warning (which may be missed among the heavy tool output). I expect such arguments to be treated as unparsed arguments and for colcon to exit with an error.

```
$ colcon build --camke-clean-cache --packages-select rcl
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL] {build,extension-points,extensions,graph,info,list,metadata,mixin,test,test-result,version-check} ...
colcon: error: unrecognized arguments: --camke-clean-cache


$ colcon build --packages-select rcl --camke-clean-cache  
[0.745s] WARNING:colcon.colcon_core.package_selection:ignoring unknown package '--camke-clean-cache' in --packages-select
Starting >>> rcl     
Finished <<< rcl [0.67s]                     

Summary: 1 package finished [1.57s]
```

**Comment by dirk-thomas** [comment]
`--camke-clean-cache` is not a valid option. Therefore `argparse` will consider it to be a package name argument since that option is greedy. So I think the behavior is expected.

Do you have a specific proposal how you imagine this to be improved?

**Comment by dirk-thomas** [comment]
Closing based on the conversation on the referenced PR: https://github.com/colcon/colcon-package-selection/pull/30#issuecomment-601431409.

**Comment by rotu** [comment]
@dirk-thomas this is still a usability issue. My proposed fix falls short of your quality standards but that doesn’t resolve the root cause

**Comment by dirk-thomas** [comment]
> this is still a usability issue. My proposed fix falls short of your quality standards but that doesn’t resolve the root cause

Atm a warning is being printed which will point the user to the problem. Without narrowing the valid package names I am not sure how it could be improved. Please feel free to make proposals how else you think it can be achieved.

**Comment by rotu** [comment]
A couple possible solutions. Do you like any of them?

1. Don't treat names starting with hyphens as possible package names. I think you don't like this solution. I do because it makes colcon behave more consistently; as it stands, package names that are a prefix to an existing command line option are a prefix to an exiting argument starting or that start with "-h" (or any other single-dash command line option) *already cause the tool to fail.*
```
colcon list --packages-select rcl "--pack"        
...
colcon list: error: ambiguous option: --pack could match --packages-ignore, --packages-ignore-regex, --packages-up-to, --packages-above, --packages-above-depth, --packages-select-by-dep, --packages-skip-by-dep, --packages-skip-up-to, --packages-select-build-failed, --packages-skip-build-finished, --packages-select-test-failures, --packages-skip-test-passed, --packages-select, --packages-skip, --packages-select-regex, --packages-skip-regex, --packages-start, --packages-end
```

```
colcon list --packages-select rcl "-not-a-package"
...
colcon list: error: argument --names-only/-n: ignored explicit argument 'ot-a-package
```

2. Treat missing package names as an error unconditionally. I don't know that this is reasonable, especially since it would mean if a package is skipped with both `--packages-skip` and a `COLCON_IGNORE` file, it would result in an error.

3. Treat missing packages as an error instead of a warning *if* they start with `"-"`. I think it's reasonable but I don't love it.

4. Require a delimiter to end list arguments, like `--packages-select foo bar -- <non-package-args>`. This would require the most invasive changes to the argument parser, but I think it's the most robust solution.

**Comment by dirk-thomas** [comment]
> 2.

Agreed with your conclusion - not reasonable.

> 3.

This kind of behavior change is very weird for a user. So I don't think it is a good choice.

> 4.

Requiring a delimiter just for the awkward use case of users misspelling arguments and getting a warning instead of a desired error is an unnecessary burden on the user. Simply because it just works without already (except the way the invalid argument is signaled).

> 1. Don't treat names starting with hyphens as possible package names. I think you don't like this solution.

When I rejected the previous proposal (#30) that was due to the implied restriction of valid package names. That kind of restriction is what I am opposed to.

> package names that are a prefix to an existing command line option or that start with "-h" (or any other single-dash command line option) already cause the tool to fail.

This is a good example of a case which should be supported (even though such a package is highly unlikely). And the same kind of problem is already being handled in other cases, e.g. when passing arbitrary arguments to another tool: https://github.com/colcon/colcon-core/blob/d6a7391cd6ed723918dcd10ce72130ac66b5fc57/colcon_core/task/python/test/pytest.py#L41 I think the same approach should work for package names:

* If a package name starts with a `-` it is being rejected at parse time of the command line arguments.
* In order to pass package names with a leading `-` the user has to quote them and prefix them with a space.

How does that sound? Are you interested in implementing this (I am mostly asking because your previous comment in https://github.com/colcon/colcon-package-selection/pull/30#issuecomment-601430496 sounded like you were not)?

**Comment by rotu** [comment]
I don’t like the leading space approach. It relies on awkward quoting and also restricts package names to not start with “ “, which doesn’t seem different from restricting them from starting with “-“.

I could implement a solution but this fix solves the problem no better for me than the rejected one in the linked PR.

**Comment by rotu** [comment]
Is this purely hypothetical or is there any project name in any package system that leads with a hyphen? Because if purely hypothetical, I’d be willing to separate solution 1 from the rest of my fork and submit a minimal PR.

**Comment by dirk-thomas** [comment]
> I don’t like the leading space approach. It relies on awkward quoting ...

You have mentioned the same preference in the previous conversation. But since you can't provide an alternative solution (which doesn't restrict the naming of packages) I will stick to this approach which has proven to work for e.g. passing arguments to tools like `cmake` / `ctest` / `pytest`.

> and also restricts package names to not start with “ “, which doesn’t seem different from restricting them from starting with “-“.

I see a pretty significant difference in these two cases. If we would really like to support a leading space in a name (which I am pretty confident no package manager does support) the logic could easily be updated to only strip the first space - so if you need to pass a package name with a leading space you just quote the name and prefix another space.

> I could implement a solution but this fix solves the problem no better for me than the rejected one in the linked PR.

I see a big difference in restricting the namespace of something (without the proper rational / reason) and making an unusual use case (a package name with a leading dash) slightly less convenient.

> I’d be willing to separate solution 1 from the rest of my fork and submit a minimal PR.

I will go ahead an implement this myself since as mentioned before the part of the previous PR doesn't address this in a way which I consider to be adequate.

Thanks for the feedback. Especially the pointed out collision with other command line arguments was helpful for me.

**Comment by rotu** [comment]
> I see a pretty significant difference in these two cases. If we would really like to support a leading space in a name (which I am pretty confident no package manager does support)

Again, do any package managers support a leading dash in a package name?

**Comment by cottsay** [comment]
> do any package managers support a leading dash in a package name?

RPM does - I just verified it locally. I can't see any package naming guidelines which forbid it in Fedora, either: https://fedoraproject.org/wiki/Packaging:Naming
