### ISSUE TITLE
Trying to install openai_ros but files not copied to install directory.

### ISSUE THREAD

**Issue by kartikye** [colcon/colcon-core#335]
Package: https://bitbucket.org/theconstructcore/openai_ros/src/kinetic-devel/

**Comment by dirk-thomas** [comment]
First, if you would like others to help you might want to consider spending a little bit more effort in describing your problem. A single sentence and a link isn't sufficient.

Second, the problem you are seeing is coming from the package you are trying to build and is not caused by `colcon`. So you might want to fill a ticket in that repository instead.
