### ISSUE TITLE
Framework-agnostic way to filter tests or test results

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#337]
It would be nice to have a way to filter tests by name when running `colcon test` or `colcon test-results`. Currently, the only way to filter tests is with things like `—pytest-args`, `—ctest-args`, and other options specific to the test’s implementation details.

**Comment by dirk-thomas** [comment]
Please consider to contribute the described feature. It would be good to first propose the desired CLI as well as the necessary extension point API to allow each test extension to provide the necessary mapping.

**Comment by rotu** [comment]
I unfortunately don't have the bandwidth or else I would have submitted a PR instead

**Comment by dirk-thomas** [comment]
I will go ahead and close this feature idea for now since:

* there is CLI to perform the task using the tool specific arguments and
* there is no expressed interest to work on this in the foreseeable future

**Comment by rotu** [comment]
> I will go ahead and close this feature idea for now since:
> 
> * there is CLI to perform the task using the tool specific arguments and
> * there is no expressed interest to work on this in the foreseeable future

The lack of manpower doesn't obviate this functional need. I believe it should remain open.

**Comment by dirk-thomas** [comment]
I will explain my rational for closing this:

> functional need

Not having this CLI option idea doesn't prevent any use cases.


> The lack of manpower

Adding a new command line option (however the desired semantic should be) is fairly simple and doesn't take much time, so "lack of manpower" doesn't apply here imo. That argument is a reason for a feature like "support profiles" but not this one.


> I believe it should remain open.

The proposed feature is just syntactic sugar. Even though you proposed it you are not willing to spend any time on it. (But you expect others to do it for you?) I certainly don't plan to spend time implementing this. And instead of keeping tickets indefinitely open if there is no wider interest for them I prefer closing them so that the open ticket can be easier triaged and acted on.
