### ISSUE TITLE
colcon-coveragepy-result package to collect coverage.py results 

### ISSUE THREAD

**Issue by christophebedard** [colcon/colcon-core#349]
I wrote a colcon extension that collects coverage.py results: https://github.com/christophebedard/colcon-coveragepy-result

* combines `.coverage` files for each package (`ros.ament_cmake` packages might have multiple files)
* optionally prints a report for each package
* combines all `.coverage` files into one
* optionally prints a global report
* generates a global HTML report

It's basically colcon-lcov-result but for Python/coverage.py.

As per the contribution recommendations, I'd like to offer to move the repo to the colcon org.

Also, feel free to take a look at the code and review/propose changes/improvements.

**Comment by dirk-thomas** [comment]
> As per the contribution recommendations, I'd like to offer to move the repo to the colcon org.

SGTM. Please transfer the repo to my username and I will transfer it from there to the `colcon` org unit.

**Comment by christophebedard** [comment]
I transfered it.

**Comment by dirk-thomas** [comment]
Thanks, I transferred it to the final destination: https://github.com/colcon/colcon-coveragepy-result

You should still have admin access to the repository. Please update the URLs in the package metadata to reflect the new location. You can do PyPI releases on your own (as before). If you would like to create Debian packages for a tagged version please create a ticket in the `colcon-coveragepy-result` for it and mention me on the ticket (since it is required to have upload access to the ROS apt repo for doing so).
