### ISSUE TITLE
Global variable should not be shared for `build` and `test`.

### ISSUE THREAD

**Issue by remod** [colcon/colcon-core#379]
Hi!

I am writing a build server script to compile ROS2 packages. In my script I both `build` and `test` packages invoking `colcon_core.command.main()`. In this scenario the `test` step fails, as the log path is not correctly created. This is due to the `build` step setting the global variable `_create_log_path_called` to `True`, therefore the `test` step does not create its own log path.

My current workaround is to reset the global variable from outside to `False` before invoking `build` or `test`.

Feel free to close the issue if you feel like this use case is too specific.

Best,
Remo

**Comment by dirk-thomas** [comment]
I haven't tried to run multiple verbs using the API in a single process. Maybe you can share a minimal reproducible example?

The logging subsystem currently assumes a single log path for the entire runtime of the script. Other codes parts might also only check the log path once and then cache it locally.

For your use case I assume the various `main()` functions could reset any global state to allow invoking multiple different ones after each other. Can you clarify why you choose to run the different invocations using the API instead of the CLI?

**Comment by remod** [comment]
Thank you for your answer!

Our CI runs one python file which invokes both the build and test steps. Of course, technically it would be possible to split it up into multiple python scripts or use `popen` to use the CLI within python, making sure the state of colcon is reset between the calls. So far, we preferred to use the API though, as it seems to be a cleaner approach for automated builds.

This is my minimal example. It throws an error regarding missing logging file/directory, but as you said, other parts of the code might also run into issues once that is fixed.

`build_and_test.py`:
```
#!/usr/bin/env python3

from colcon_core.command import main as colcon_main

colcon_main(argv=['build'])
colcon_main(argv=['test'])
```

Build and test the ROS2 example interfaces package:

```
cd workspace
git clone git@github.com:ros2/example_interfaces.git
source /opt/ros/foxy/setup.bash
./build_and_test.py
```

Error message:
```
No such file or directory: '{....}/log/test_2020-09-07_06-34-05/logger_all.log'
```

**Comment by dirk-thomas** [comment]
Please see #391 and colcon/colcon-output#37 for proposed patches. It would be great if you could try them and comment if they resolve the problem with your use case. Thanks.
