### ISSUE TITLE
Python package with explicit type fails to build when using package_dir

### ISSUE THREAD

**Issue by Danmou** [colcon/colcon-core#384]
### MWE
```
foo/
├── colcon.pkg
├── setup.py
└── src
    └── foo
        └── __init__.py
```
`colcon.pkg`:
```yaml
name: foo
type: python
```
`setup.py`:
```python
from setuptools import find_packages, setup

setup(name='foo',
      packages=find_packages('src'),
      package_dir={'': 'src'})
```

### Results
With this setup, I get the following:
```
$ colcon build
Starting >>> foo
--- stderr: foo
error: error in 'egg_base' option: 'src' does not exist or is not a directory
---
Failed   <<< foo [0.32s, exited with code 1]

Summary: 0 packages finished [0.42s]
  1 package failed: foo
  1 package had stderr output: foo

$ ls build/foo
colcon_build.rc                    colcon_command_prefix_setup_py.sh.env
colcon_command_prefix_setup_py.sh  setup.py
```
Note that `src` is missing from the build directory.

If I remove `type: python` from `colcon.pkg` it works fine:
```
$ colcon build
Starting >>> foo
Finished <<< foo [0.77s]

Summary: 1 package finished [1.14s]

$ ls build/foo
colcon_build.rc                    colcon_command_prefix_setup_py.sh.env  src
colcon_command_prefix_setup_py.sh  setup.py
```

**Comment by dirk-thomas** [comment]
The question / problem is not related to `colcon`. The same error would occur if you try to invoke the native instructions: `python(3) setup.py install`.

The error message:

> `error: error in 'egg_base' option: 'src' does not exist or is not a directory`

indicates that there is no Python module `src` exists under the directory `src`.

The `package_dir` argument tells Python that all modules (`''`) are to be found in a subdirectory (`'src'`) which is okay.
But `packages=find_packages('src')` tells Python to look for a Python module `src` within that subdirectory.

So you want to use `packages=find_packages()` which will automatically find all Python modules under the `src` subdirectory.

---

Commonly Python packages don't use a `src` subdirectory. In your case you could move the `foo` directory one level up and then don't need to declare `package_dir` anymore.

---

Btw you shouldn't need a `colcon.pkg` file. Since the package contains a `setup.py` file `colcon` should automatically detect the type as well as the name.

**Comment by Danmou** [comment]
@dirk-thomas That's not true. The argument to find_packages is _where_ to look for packages, see https://setuptools.readthedocs.io/en/latest/userguide/package_discovery.html#using-find-or-find-packages. This is a perfectly normal usage.

As you can see from my example, the behavior is different when you explicitly specify type, which shouldn't happen. I need to override the type because I need to have a package.xml for legacy reasons but I don't want colcon to build it with catkin.

**Comment by Danmou** [comment]
I just checked and the problem does happen only when using a different `package_dir`. However, this structure is very common and supported by distutils/setuptools, so it should also be supported by colcon.

**Comment by dirk-thomas** [comment]
> That's not true. The argument to find_packages is where to look for packages

> I need to override the type because I need to have a package.xml for legacy reasons but I don't want colcon to build it with catkin.

You can add a `build_type` tag within the `export` tag in the `package.xml`. I don't think there is a `python` value but I would suggest trying `ament_python`.

**Comment by dirk-thomas** [comment]
> That's not true. The argument to find_packages is where to look for packages

You are right. I read it as `find_package(include=...)`.

> I need to override the type because I need to have a package.xml for legacy reasons but I don't want colcon to build it with catkin.

You can add a `build_type` tag within the `export` tag in the `package.xml`. I don't think there is a `python` value but I would suggest trying `ament_python`.

> I just checked and the problem does happen only when using a different `package_dir`.

#272 is similar in that regard but only covers a small aspect. I will reopen the ticket and update the title to reflect the actual problem.

**Comment by dirk-thomas** [comment]
@Danmou Are you passing `--symlink-install` when you run into this?

**Comment by dirk-thomas** [comment]
The reason for the failure is that setting the package type explicitly to `python` in the `colcon.pkg` file bypasses the `PythonPackageIdentification` extension which usually extracts the metadata from the package (e.g. `packages` and `package_dir`). Without those the following invocation of `setup.py develop` fails since the sources haven't been symlinked into the build directory.

I wonder if the metadata extraction part of the identification extension should be moved into an augmentation extension in order to always be performed in case the type is explicitly set like this.

**Comment by Danmou** [comment]
> @Danmou Are you passing `--symlink-install` when you run into this?

Yes, although I believe I got the same result without it.

**Comment by Danmou** [comment]
> I wonder if the metadata extraction part of the identification extension should be moved into an augmentation extension in order to always be performed in case the type is explicitly set like this.

That sounds like the right approach.

**Comment by dirk-thomas** [comment]
@Danmou Please see #385 and colcon/colcon-python-setup-py#40 which together should resolve this problem. It would be great if you could try your use case with those and comment with your result.

**Comment by Danmou** [comment]
I can confirm that this solves the original issue. However, I discovered another issue when trying it on my actual use case: #388
