### ISSUE TITLE
Python package scripts are missing when using symlink-install

### ISSUE THREAD

**Issue by Danmou** [colcon/colcon-core#388]
### MWE
```
foo
├── scripts
│   └── bar.py
└── setup.py
```
`setup.py`:
```python
from setuptools import setup
setup(name='foo', scripts=['scripts/bar.py'])
```
`bar.py`:
```python
#!/usr/bin/env python3
print("hello world")
```

### Results
With normal build it works:
```
$ colcon build
Starting >>> foo
Finished <<< foo [0.59s]

Summary: 1 package finished [1.09s]
```

but with `--symlink-install` it fails:
```
$ colcon build --symlink-install
Starting >>> foo
--- stderr: foo
error: [Errno 2] No such file or directory: '/home/daniel/test/build/foo/scripts/bar.py'
---
Failed   <<< foo [0.65s, exited with code 1]

Summary: 0 packages finished [1.16s]
  1 package failed: foo
  1 package had stderr output: foo
```

**Comment by dirk-thomas** [comment]
Thanks for the report. I can see why that was never discovered since many packages it has been used for are using `console_scripts` entry points in order to generate an invocable executables across platforms.

Please see #389 for a proposed patch. It would be great it you could try it and comment if it works for your use case.

**Comment by Danmou** [comment]
@dirk-thomas Sorry for the delay, I've confirmed that this fixes the problem on my original use case as well.
