### ISSUE TITLE
All Travis builds failed overnight on an import error relating to pytest

### ISSUE THREAD

**Issue by tfoote** [colcon/colcon-core#392]
It looks like cron based trigger not a code based trigger failed all the jobs which suggests that something in the dependencies changed behavior. A snippet of the backtrace from https://api.travis-ci.org/v3/job/730824136/log.txt
```
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
    exec(co, module.__dict__)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pytest_rerunfailures.py", line 7, in <module>
    from _pytest.resultlog import ResultLog
ImportError: No module named '_pytest.resultlog'
```

**Comment by tfoote** [comment]
This has been triaged upstream: https://github.com/pytest-dev/pytest-rerunfailures/pull/129 We're hoping for a new release soon.

**Comment by dirk-thomas** [comment]
This is due to the release of `pytest` 6.1.0: https://github.com/pytest-dev/pytest/blob/6.1.0/doc/en/changelog.rst#pytest-610-2020-09-26

The problem in `pytest-rerunfailures` has been reported in pytest-dev/pytest-rerunfailures#128 and already been fixed on `master`. Therefore I would expect a new release from coming soon which should resolve the problem.

**Comment by dirk-thomas** [comment]
This has been resolved with a new release of `pytest-rerunfailures`: 9.1.1.
