### ISSUE TITLE
0.6.2 release for symlink support

### ISSUE THREAD

**Issue by Timple** [colcon/colcon-core#440]
Symlinks in the workspace where broken (#406 #412). Now and then a colleague runs into this issue.

These PR's where part of release [0.6.2](https://github.com/colcon/colcon-core/milestone/49)
Since 0.6.2 is finished. Could this be released?

**Comment by Timple** [comment]
Any update?

**Comment by mikepurvis** [comment]
I'd love to see a release as well; the previous was almost a year ago and several important fixes have gone in in that time.

@cottsay, @sloretz Are you able to make it happen?

**Comment by dirk-thomas** [comment]
Since I don't have the spare time to do any work on colcon these days I won't tell other what to do or not to do.

But a (fairly significant) concern I would have: the Travis CI integration for all colcon repositories has been broken for a while. Merging any changes and making releases without that safety net has an increased risk to introduce regressions. I strongly suggest to first "get the house in order" and reestablish CI coverage for the lost platforms - e.g. by adding GitHub action support to all repos.
