### ISSUE TITLE
colcon list --packages-up-to selects local exec_depend too

### ISSUE THREAD

**Issue by asasine** [colcon/colcon-core#452]
I've noticed when building or listing package dependencies, specifying a package with `colcon build --packages-up-to my_package` also selects any listed `<exec_depend>` in the _package.xml_ file if that package is located in the base paths.

Example:
```text
ws/
  src/
    my_package/
      package.xml
    my_exec_depend/
      package.xml
```

and _ws/src/my_package/package.xml_ contains:
```xml
<?xml version="1.0"?>
<package format="2">
  <name>my_package</name>
  <version>0.0.1</version>
  <description>My package</description>

  <!-- etc -->

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>my_exec_depend</exec_depend>
  <exec_depend>some_rosdep_dependency</exec_depend>
</package>
```

When I run `colcon list --packages-up-to my_package`, I get both `my_package` and `my_exec_depend` but not `some_rosdep_dependency`.

```text
$ colcon list --packages-up-to my_package
my_exec_depend  src\my_package  (ros.catkin)
my_package      src\my_exec_depend      (ros.catkin)
```

I expected to either get `my_package` alone, or all exec dependencies. Can anyone provide some insight as to why this behavior exists?

**Comment by mikepurvis** [comment]
It doesn't select a package that doesn't exist in the workspace.

But some of your confusion may be stemming from a curiosity of dependencies in catkin-world that is somewhat inherited from the underlying reality of these dependencies mapping down into deb package dependencies, and that is that the package v1 "run_depend" had a dual role:

- A run_depend might be "I need X for when my executables are run", or
- A run_depend might be "things that have me as a build_depend need to have X too."

With a deb package, this distinction doesn't matter, since either way, you just install the package. But in workspace builds, it leads to some funkiness where you can unexpected get run/exec depends built when you think it should only have have built the build_depend tree. In an attempt to clear some of this up, package xml format 2 split the run_depend into separate exec_depend and build_export_depend, but the underlying implementation papers over the difference, such that in many cases it is still read as the old `run_depends` and any genuine distinction is lost:

https://github.com/ros-infrastructure/catkin_pkg/blob/20164bb3d67be3370a52177bb717458a868a1250/src/catkin_pkg/package.py#L116-L123

The corresponding logic in colcon-ros does exactly the same collapsing into a single run_depends bucket:

https://github.com/colcon/colcon-ros/blob/eb0b932cf7b1f3f5a720804e67f3c1a0f8995ca8/colcon_ros/package_identification/ros.py#L92-L100

I know that doesn't directly answer the question, but hopefully it's some helpful context.

**Comment by asasine** [comment]
Thanks for the context, this is exactly what I was looking for!

Is there a way to configure the package.xml (format 2 or 3) to exclusively list a package as "I need X for when my executables are run" ?

**Comment by mikepurvis** [comment]
That is the intention for `exec_depend`, but as I say, unfortunately no current tooling is able to do anything meaningful with that information.
