### ISSUE TITLE
Repo Creation Request: `colcon-hardware-acceleration` (PENDING REPO)

### ISSUE THREAD

**Issue by methylDragon** [colcon/colcon-core#493]
## Request Description
The Hardware Acceleration Working Group @ros-acceleration has made a [repository](https://github.com/ros-acceleration/colcon-hardware-acceleration) for introducing some colcon verbs for hardware acceleration, mostly authored by @vmayoral.

Could the package be transferred to the `colcon` org, or a new one made that the extensions can be slated for release?

Is transferring the repo or creating a new one preferred? I think either way @vmayoral has to handle the transfer process...

The work to get it ready for release is tracked in this issue: https://github.com/ros-acceleration/colcon-acceleration/issues/10

## Additional Notes
There's a pending draft [REP-2008](https://github.com/ros-infrastructure/rep/pull/324) that this extension package is a part of the implementation for, but I'm not sure if the pending status of the REP will factor into the decision to pull this package into the `colcon` org or slate it for release.

**Comment by cottsay** [comment]
Overall, I think this extension is in fairly good shape. I'd like feedback from other colcon folks about the name `colcon-acceleration`, as the name isn't specific to Hardware Acceleration so might be confusing.

Some specific points:
- [x] Licensing looks good. Apache 2.0.
- [x] No ridiculous overhead for additional entry points - only a single verb.
- [ ] Should advertise a `colcon_core.extension_point` entry point for the `colcon_acceleration.subverb` extension point.
- [ ] Should either drop the `tests_require` or add SOME tests. Copyright checks would be highly recommended. It looks like it might be "too late" for flake8 without some substantial investment, so probably best to drop the flake8 section from the setup.py if it's not going to get used.
- [ ] The `stdeb.cfg` should be updated to align with other colcon repositories (namely the `Suite` list).
- [ ] The `README.rst` should be dropped if a `README.md` is used.

**Comment by vmayoral** [comment]
> - [ ] Should advertise a colcon_core.extension_point entry point for the colcon_acceleration.subverb extension point.

https://github.com/ros-acceleration/colcon-acceleration/commit/48efc96f8a3594bc68855f5a46fb111b08927d0f fullfills it.

**Comment by vmayoral** [comment]
>  Should either drop the tests_require or add SOME tests. Copyright checks would be highly recommended. It looks like it might be "too late" for flake8 without some substantial investment, so probably best to drop the flake8 section from the setup.py if it's not going to get used.

- https://github.com/ros-acceleration/colcon-acceleration/commit/3e69285c0145ff5c4b6a71602d0986dbcaee7020
- https://github.com/ros-acceleration/colcon-acceleration/commit/c03e8ca916113981acc6188cb3bbb65ad2db5780

Get us to to some basic tests for the package. Let me know @cottsay if you're missing anything else.

**Comment by vmayoral** [comment]
https://github.com/ros-acceleration/colcon-acceleration/commit/6d4ddbaaee5e66d67743e8e299c35e3f547507b5 cleans up flake8 deps which aren't needed for now and adds `publish-python.yaml` file.

**Comment by methylDragon** [comment]
Ok, looks ok to me. I think once this gets integrated, I'll open an issue for refinements.

**Comment by wjwwood** [comment]
@cottsay asked for feedback on the naming internally, so...

It seems to me that just "colcon-acceleration" is pretty generic. I know that's what's been used in the "ros-acceleration" branding, but did you guys consider something more specific like "hardware acceleration"? Even that is kind of vague, because if I hear "colcon-acceleration" my first thoughts are nothing to do with enabling hardware acceleration for the software being built. Instead, it seems like it should accelerate some part of colcon or the build process...

I'm not 100% sure what the role of colcon is in enabling this functionality either. Perhaps the question should be "does this belong in colcon"? For instance, CLI things like `vcs` and `rosdep` are not part of colcon and I think that's a good thing, to be honest. Maybe this should just be its own set of CLI scripts that don't use colcon? Maybe that doesn't make sense given the technical requirements, but I'm not up to speed on those.

Not a blocker, but I'm +0 leaning towards -1 on the name due to how generic it is.

**Comment by nuclearsandwich** [comment]
I also have been hung up on the "Acceleration" name in the context of the ros2-gbp team name. I would recommend something like `hardware_acceleration` or `hw_accleration` or even `hwa` but ultimately left it as is with `acceleration_wg` (where wg == working group) because [ros-acceleration](https://github.com/ros-acceleration) is the name of the upstream org.

For colcon, which is not exclusively a ROS community project I think there's even more weight behind specificity since there is no immediate mapping between the colcon extension and ROS organization via the team / working group name.

**Comment by vmayoral** [comment]
I'm open to renaming from `colcon-acceleration` to `colcon-hardware-acceleration` if that gets us moving forward. Let me know if that'll do.

**Comment by methylDragon** [comment]
I think with rename we're good to go

There's small naming changes in the README that can be done, but I'll mention it in the issue. (:

**Comment by vmayoral** [comment]
All right, thanks everyone for the comments:

- [x] rename repo to `colcon-hardware-acceleration`
  - [x] Make appropriate changes to adapt source code 3a1b3e18e225c0acf97c1bac5e6d4bc4cce81533
- [x] Replace *ROS workspace* mentions for *colcon workspace* ones in README bc3ca604dd0b4fda2d1b7782da5705ccd069f049
- [x] released 0.6.0 989a451fb54a60dffdca23b708563d08df317b4f
- [x] created a new tag for it

I kept the `acceleration` verb in https://github.com/ros-acceleration/colcon-hardware-acceleration/blob/main/setup.cfg#L47 because I'd like to type as little as possible but if we **really** need to change this now (we can always go change the verb afterwards if another "acceleration" use case appears), I'd suggest `hwacceleration` instead of `hardware_acceleration`.

**Comment by methylDragon** [comment]
I wonder if `hwa` is possible to use if `acceleration` is an issue?

**Comment by vmayoral** [comment]
> I wonder if hwa is possible to use if acceleration is an issue?

Mmm let me check internally and think about it. Before I dig too deep, is `acceleration` an issue?

**Comment by methylDragon** [comment]
I'm not sure yet, will need to see what the team thinks.

**Comment by nuclearsandwich** [comment]
> Mmm let me check internally and think about it. Before I dig too deep, is `acceleration` an issue?

I have a strong preference for `hwa` over `acceleration` for the verb name. I find it both more specific and easier to type at the cost of being slightly more opaque ("what's a Hwah?") but that's a _preference for_ `hwa` not an outright _objection to_ `acceleration` as a colcon verb.

**Comment by vmayoral** [comment]
If there's no strong objection, may I suggest we stick with `acceleration` as a colcon verb? there's quite a bit of documentation and content generated around it already and it'll be a bit painful 😭 to change it all again (we already changed it a while ago from `krs` to `acceleration` to make it more *generic* and community-accepted).

**Comment by methylDragon** [comment]
Repo migrated! https://github.com/colcon/colcon-hardware-acceleration

Thanks for the support here! We'll move on with the release steps, but I'll close this issue for now.
