### ISSUE TITLE
Repo Transfer Request: `colcon-clean`

### ISSUE THREAD

**Issue by ruffsl** [colcon/colcon-core#521]
## Request Description

I've authored a colcon extension named `colcon-clean` to introduce a new `clean` verb to the colcon CLI:

> An extension for [colcon-core](https://github.com/colcon/colcon-core) to clean package workspaces. Enables cleaning of various colcon paths, such as build or install folders, for either the entire workspace or for selected packages with advanced path globing options. In conjunction with [colcon-package-selection](https://github.com/colcon/colcon-package-selection), this extension can help maintain hygienic build environments while leveraging persistent workspaces for caching by allowing users to finely remove stale artifacts, preserving what can be cached during software development. For example, when pulling various changes into a local workspace to review pull requests, this extension can be used to wipe only the build and install paths for affected packages, ensuring subsequent builds are not cross contaminated from previous jobs.

The repo, demo, and talk for this extension can be viewed here: 

- https://github.com/ruffsl/colcon-clean
- https://gist.github.com/ruffsl/b2b567995810c69866221f659d52e71e
- https://vimeo.com/649647161/5b0c278e6c

Could this extension be transferred to the `colcon` org and be slated for release?

## Additional Notes

This relates to some long standing tickets, including:

- https://github.com/colcon/colcon-core/issues/37
- https://github.com/ms-iot/vscode-ros/issues/554
- https://github.com/colcon/colcon-core/issues/213

The extension's release was previously blocked in debian, but has since be resolved:

- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002306

This extension is already being used in the wild:

- https://github.com/ros-planning/navigation2/pull/2399
- https://discourse.ros.org/t/experiences-with-ros-2-on-our-robots-and-what-we-learned-on-the-way/26637

**Comment by cottsay** [comment]
From what I can tell, we will only be able to build a debian for Jammy, which is the only supported Ubuntu version where `python3-scantree` is released: https://packages.ubuntu.com/search?keywords=python3-scantree&searchon=names&suite=all&section=all

**Comment by ruffsl** [comment]
Indeed. While I manage to upstream some python dependencies into the recent release of debian, we'd have to packing and host those in the ros apt repo if we'd want to backport these extensions to prior distros. That said, I'm unsure of the colcon version differences between distros, or if there would be any API breaks.

**Comment by kledom** [comment]
I don't want to sound rude or anything. But are there any plans here for what happens next?

It's hard for me to understand why, after several years of development, colcon still can't have a "clean" command. A feature that at least any other buildtool that I've heard of has. Hopefully, the problem cannot be any dependencies on some python library?

**Comment by cottsay** [comment]
I started reviewing the extension last week. I'm on vacation for the next week, but I can take a look after that.

You are 100% able to install the extension from pip right now.

**Comment by kledom** [comment]
Thanks for the update.
I know that I can install the extension via pip. Maybe it's just me, but mixing apt-installed packages with pip extensions sounds dangerous to me. Also, I would argue that `clean` should be a basic feature of colcon and come pre-installed (or at least with colcon-common-extensions). Even if typing some `rm` command doesn't seem that complicated, `clean` offers a certain extra comfort.

**Comment by nuclearsandwich** [comment]
> Maybe it's just me

I think that this is part of the equation worth focusing on. Colcon itself, [by design](https://colcon.readthedocs.io/en/released/developer/design.html) is not meant to be a kitchen sink system which builds in everything anyone could possibly want, instead it's built ground up as an extensible system.

To me, colcon is not meant to be "universal" like a black hole absorbing everything in its gravitional pull but universal like interlocking brick toys, allowing its users to build exactly the thing they need for a given situation.

Right now there's no set criteria for what gets included in colcon-common-extensions and I expect it will always be at the discretion of the maintainers of that package, but what you consider essential intersected with what everyone else considers essential would eventually encompass every available colcon extension. If colcon-common-extensions doesn't cover the cases you want, it's entirely possible for you to create your own similar metapackge that includes your preferred colcon extensions. I recognize that right now this is stymied by colcon-clean not yet being published in the colcon apt repositories but this is something that we'll hopefully resolve soon.

**Comment by ruffsl** [comment]
@cottsay , any remaining topics to review before releasing this extension?

- [x] Fix declared target dependencies
- [x] Port CI to colcon/ci
  - [x] Fix extension for windows
- [x] Max out code coverage

Should I now transfer ownership to the colcon github org?

**Comment by cottsay** [comment]
This one is good to go. If it won't let you do it, grant me 'owner' on the original repo and I'll transfer it.

**Comment by cottsay** [comment]
@ruffsl, if you're ready, I'd like to transfer this extension into the `colcon` org now.

**Comment by ruffsl** [comment]
> @ruffsl, if you're ready, I'd like to transfer this extension into the `colcon` org now.

Done! If you could add me back to the repo, that'd also cool.

**Comment by Niknu** [comment]
Is this closed now or not?

**Comment by cottsay** [comment]
The package still needs to be tagged and released.

**Comment by ruffsl** [comment]
This package has been released: https://github.com/colcon/colcon-clean/issues/31#issuecomment-1347186325
