### ISSUE TITLE
Crawling packages fails on Windows machine.

### ISSUE THREAD

**Issue by agaertner** [colcon/colcon-core#543]
Hey,

crawling suddenly fails on my windows machine (I am usually using Linux).

At first it worked but now I cannot get it to work ever. I even reinstalled ROS2-Humble and cleaned my environments.

1. I have reinstalled python and created a virtual environment.
2. Installed all neccessary ROS2_Humble packages and ``colcon-common-extensions``.

3. I source Visual Studio env and ROS2.
4. Go into my workspace and do "colcon build --symlink-install" as usual and it won't find any packages even though my packages are located there and it should find them when searching the folders recursively. On my other workstation (Linux) it always works.

At first it failed silently but in the trial within a fresh venv I got:
```
(venv-minirov) PS F:\ros2_humble\ros2_ws> colcon build --symlink-install

Summary: 0 packages finished [0.14s]
WNDPROC return value cannot be converted to LRESULT
TypeError: WPARAM is simple, so must be an int object (got NoneType)
```

**Comment by cottsay** [comment]
Can you please take a look at the verbose output using `colcon --log-level debug list` or the like? It might be too much output to post here, but maybe the first several lines would be helpful.

**Comment by agaertner** [comment]
First, I had spaces in my setup.bat causing some variables not getting set (ie ``set myVar = "path/to/env.bat"`` failed due to the spaces around the assignment operator..... ``set myVar="path/to/env.bat"``. This out of the way I found that
``--symlink-install`` doesn't report as much as a normal copy install does. When I tried once again it showed me that I forgot to run the VisualStudio environment beforehand so that ``VisualStudioVersion`` is set. 

Now that I run the ``vcvarsall.bat x86_64`` it finds my packages.

However, I encountered some other issues with python linking unrelated to colcon but ros2 using a virtual python env and some libraries like ``em conflicting with empy`` and after hours I gave up on Windows and just created VM for now. 
Sadly WSL2 is too unstable still (Already have that behind me. Even build a custom linux kernel for getting xbox controllers to work with that crappy xbox interface).

I will just stop trying to make Windows work for anything outside of the C# Asp.Net domain. Just not worth the hassle.

Might just create a dual-boot later.  

I wrote this just so if anyone is trying to make Windows work for anything related to science. Stop.

Thanks for the help.

**Comment by cottsay** [comment]
> log from `F:\ros2_humble\ros2_ws\log\list_2022-12-21_10-55-02`

This output [suggests](https://github.com/colcon/colcon-core/blob/master/colcon_core/package_identification/__init__.py#L145) that the working directory (`F:\ros2_humble\ros2_ws`) contains an [ignore marker](https://github.com/colcon/colcon-core/blob/de688c971a8e114315dfaf8faed351d669316300/colcon_core/package_identification/ignore.py#L11), which explains the behavior you're experiencing.

Is it possible that you attempted to set the `--install-base` or `--build-base` to that directory instead of a subdirectory, which would have automatically created an ignore marker?

> I had spaces in my setup.bat causing some variables not getting set

This sounds like a bug to me, but I can't find any such occurrences across any colcon or ament packages. Can you help me track it down?

> ...I found that `--symlink-install` doesn't report as much as a normal copy install does.

This shouldn't be the case, especially for CMake projects. I'm not booted into Windows right now so I can't give it a shot, but the console output on Linux is identical for `--symlink-install`, except that the `Installing` messages are replaced with `Symlinking` ones.

I'd like to encourage you to try following the [official build guide](https://docs.ros.org/en/rolling/Installation/Alternatives/Windows-Development-Setup.html) for ROS 2 on Windows. I've personally run through these instructions recently and was able to compile ROS 2 successfully.

**Comment by agaertner** [comment]
Yes, I am usually setting ``--install-base`` and ``--build-base`` to my ``ros2_ws`` and source my package setup script. I have done so on my Linux workstation as well without issues. Indeed I was wondering why it always created a ``COLCON_IGNORE`` after I called ``colcon build``. Is there something in the docs about that?

> I had spaces in my setup.bat causing some variables not getting set
>> This sounds like a bug to me, but I can't find any such occurrences across any colcon or ament packages. Can you help me track it down?

Don't worry. That's just a batch syntax thing. Simply removing the spaces around the assignment fixed it.

> I'd like to encourage you to try following the [official build guide](https://docs.ros.org/en/rolling/Installation/Alternatives/Windows-Development-Setup.html) for ROS 2 on Windows. I've personally run through these instructions recently and was able to compile ROS 2 successfully.

I am usually following these instructions, thank you. I might have forgotten to install the ``xmllint`` stuff under *Install miscellaneous prerequisites*. 

After I cleaned my entire Windows machine I gave it another go and now it seems to build.
