### ISSUE TITLE
I can't add Travis to colcon-gradle

### ISSUE THREAD

**Issue by esteve** [colcon/colcon-core#89]
I don't know if it's because I'm not a member of the `colcon` organization or because I'm not an owner of `colcon-gradle`, but either way I can't seem to be able to add Travis to my repo.

I'd also ask to be owner of the repo, which IMHO makes sense given that I'm the one working on it.

**Comment by dirk-thomas** [comment]
As far as I know there is no such thing as "owner of the repo". There is only an owner role on the org unit (which seems to be a little bit to broad) You already have the permission level "admin" for the `colcon-gradle` repository which is the highest one.

Have you tried to add Travis CI under https://github.com/colcon/colcon-gradle/settings/installations ? For `colcon-cargo` the admin user seem to have been able to set it up without a problem.

**Comment by dirk-thomas** [comment]
The recent commits on the `colcon-gradle` repo seem to have Travis CI checks. Therefore I am going to close this ticket.

**Comment by esteve** [comment]
Unfortunately I had to use the legacy version of Travis (https://travis-ci.org/ which is being deprecated), not the new one (https://travis-ci.com/) that uses GitHub apps. Same goes for `colcon-cargo` (https://travis-ci.org/colcon/colcon-cargo). Please reopen the ticket.

**Comment by dirk-thomas** [comment]
According to [this blog](https://blog.github.com/changelog/2018-04-30-github-app-installation/) you should be able to request the installation of a GitHub app for the repository since you are a member of the org unit. Unfortunately it doesn't contain and instructions or links but maybe you find something in the repository settings or through Travis?

**Comment by esteve** [comment]
Thanks! I'll look into that, in the meantime I'll continue using https://travis-ci.org until I figure out how to migrate it to the https://travis-ci.com

**Comment by dirk-thomas** [comment]
Recently the maintainer of the `colcon-bazel` package requested to install the `Codecov` app which I was able to approve. So it seems that the process does seem to work.

Assuming this will be the same for the Travis CI app and there is nothing which needs to be done in this repository I will close this again.

**Comment by esteve** [comment]
That's strange, I can't see the `colcon` organization on Codecov either. I do see EpicGames (see screenshot attached), for which I don't have any special permissions, I just happen to be a member of a team within the EpicGames organization. Perhaps I need to be added to a team within the `colcon` org for this to work?

![codecov_teams](https://user-images.githubusercontent.com/33620/44223721-ed58cc80-a177-11e8-8c9f-c41595a9c8a0.png)

**Comment by dirk-thomas** [comment]
The repositories are being whitelisted one-by-one in the app settings. Currently only the `colcon-bazel` is listed. If you want additional repos to be enabled you can either request this through a ticket like this or (I don't know if that works since I haven't tried it) request the installation of the app for your repo through the GitHub settings.
